# Generated by Django 3.2.4 on 2021-06-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('apellido_paterno', models.CharField(default='DEFAULT VALUE', max_length=30)),
                ('apellido_materno', models.CharField(default='DEFAULT VALUE', max_length=30)),
                ('puesto', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('apellido_paterno', models.CharField(default='DEFAULT VALUE', max_length=30)),
                ('apellido_materno', models.CharField(default='DEFAULT VALUE', max_length=30)),
                ('fecha_nac', models.DateTimeField()),
                ('direccion', models.CharField(default='DEFAULT VALUE', max_length=30)),
                ('num_cel', models.IntegerField()),
                ('img', models.FileField(default='', upload_to='')),
                ('semestre', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('horario_alumno', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('apellido_paterno', models.CharField(default='DEFAULT VALUE', max_length=30)),
                ('apellido_materno', models.CharField(default='DEFAULT VALUE', max_length=30)),
                ('asignatura', models.CharField(max_length=20)),
                ('img', models.FileField(upload_to='')),
                ('horario', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'maestro',
            },
        ),
    ]
