# Generated by Django 3.2.4 on 2021-06-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_auto_20210626_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='num_cel',
            field=models.CharField(max_length=16),
        ),
    ]
