# Generated by Django 3.2.4 on 2021-06-26 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_alter_alumno_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='img',
        ),
    ]
