# Generated by Django 3.2.4 on 2021-06-26 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0005_remove_alumno_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Alumnos',
        ),
        migrations.AlterModelTable(
            name='alumnos',
            table='alumnos',
        ),
    ]
