# Generated by Django 3.2.4 on 2021-06-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0006_auto_20210626_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='maestro',
            name='img',
        ),
    ]
